name: Build and Push Docker Image

on:
  push:
    branches:
      - master

  workflow_dispatch:  # <--- Добавляет кнопку "Run workflow"

env:
  IMAGE_NAME: 4tt-new-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Output image URL
        run: echo "✅ Image pushed to ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
